# Generated by Django 2.1.2 on 2018-10-13 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dados',
            old_name='dispositivo_id',
            new_name='dispositivo',
        ),
    ]
