# Generated by Django 2.1.2 on 2018-11-01 03:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181013_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 1, 3, 7, 30, 587000)),
        ),
    ]
